ACLの実験レポートの追加
CIT-NakamuraLab/Network-Infrastructure-Experiments pull request #10
Opened 2022-08-29 01:02 UTC by kenshin-yamamoto

初めてPullRequestしたので正しくできているのか分かりません。
間違っている点があれば教えてください。

2022-08-29 14:07 UTC, NakagawaRyunosuke requested changes
インバウンドで設定する場合とアウトバウンドで設定する場合の違いの説明があると良いと思います。

2022-08-29 14:07 UTC, NakagawaRyunosuke commented on 20220730-ACL.md
> +192.168.0.0/24のネットワークからWebサーバへの通信のうち、icmpとtcpのポート番号2022のみの通信を許可するACLをFE8のインパウンドに、192.168.100.0/24のネットワークからWebサーバへの通信のうち、tcpのポート番号80のみの通信を許可するACLをFE7のインバウンドに適用し、それ以外の通信は拒否するACLを、なるべく記述を減らして記述する。
誤字がありました。
× インパウンド
○ インバウンド

2022-09-01 02:12 UTC, kenshin-yamamoto commented
@NakagawaRyunosuke 
確認ありがとう!
違いについて追記したので確認お願いします

2022-09-01 02:24 UTC, quadseed approved these changes
LGTM!

2022-09-01 03:27 UTC, NakagawaRyunosuke approved these changes
LGTM!

2022-09-01 05:30 UTC, oz-0820 approved these changes
👍

2022-09-01 12:07 UTC, Shunsuke-Torus reviewed
LGTM👍

2022-09-01 14:07 UTC, Ryosei-IT commented
👌👌

2022-09-01 14:14 UTC, Ryosei-IT reviewed
👌👌👌👌

2022-09-01 20:01 UTC, AInine9 approved these changes
OK!!

2022-09-01 23:33 UTC, merged