8/22 STP ナレッジ部分
CIT-NakamuraLab/Network-Infrastructure-Experiments pull request #11
Opened 2022-09-10 17:39 UTC by AInine9

## What's this PR do?
- 8/22日に行ったSTPの実験のナレッジ部分のレポートを追加

## How to Check
- レポート内容の正誤確認
- 誤字脱字のチェック

2022-09-12 17:19 UTC, quadseed requested changes
コメントした点について確認してください

2022-09-12 17:19 UTC, quadseed commented on 20220822-STPknowledge.md
> +STPでは2秒ごとにBPDUを送信するタイマーによる管理を行っているが、RSTPではスイッチ間で直接やり取りして役割を決定する。ルートブリッジからBPDUを受け取ったときに下流のスイッチに送信するのではなく、それぞれのスイッチがBPDUをを作成して下流のスイッチに送信する。また、構成の変更が検知された際も、そのスイッチが他のスイッチに変更を通知する。
文字が重複しています

69行目 `それぞれのスイッチがBPDUをを作成して`

2022-09-13 13:19 UTC, AInine9 commented on 20220822-STPknowledge.md
> +STPでは2秒ごとにBPDUを送信するタイマーによる管理を行っているが、RSTPではスイッチ間で直接やり取りして役割を決定する。ルートブリッジからBPDUを受け取ったときに下流のスイッチに送信するのではなく、それぞれのスイッチがBPDUをを作成して下流のスイッチに送信する。また、構成の変更が検知された際も、そのスイッチが他のスイッチに変更を通知する。
訂正しました！
ご確認お願いします。

2022-09-13 13:21 UTC, quadseed approved these changes
良いと思います

2022-09-15 12:39 UTC, merged