edit 20220711-ospf.md
CIT-NakamuraLab/Network-Infrastructure-Experiments pull request #6
Opened 2022-08-19 13:30 UTC by NakagawaRyunosuke

構築手順の説明の際に一部改行が反映していなかったため修正

2022-08-19 15:33 UTC, quadseed requested changes
以下の点について確認してください

2022-08-19 15:33 UTC, quadseed commented on 20220711-ospf.md
> +④	他のルーターにも①〜③を行う
変更が反映されていない（mainブランチと変化がない）ようです。

2022-08-20 14:12 UTC, NakagawaRyunosuke commented on 20220711-ospf.md
> +④	他のルーターにも①〜③を行う
訂正しました、確認お願いします。

2022-08-21 04:32 UTC, quadseed approved these changes
Good

2022-08-21 10:36 UTC, merged