NAT/DHCPブランチ名の変更
CIT-NakamuraLab/Network-Infrastructure-Experiments pull request #9
Opened 2022-08-27 07:24 UTC by Ryosei-IT

スラッシュ入りだったのでブランチ名を変更しました。

2022-08-27 07:29 UTC, Ryosei-IT commented
画像が表示されないのでブランチ名変更したりしてみたのですが、治らずよくわかりません。。助けて下さい。。

2022-08-27 12:27 UTC, quadseed commented
@Ryosei-IT 
画像が表示されない理由は、画像ファイルの相対パスが完全に一致していないからです。
誤: `![実験環境](images/20220809NAT_DHCP/NAT2.jpg)`
正: `![実験環境](images/20220809NAT_DHCP/NAT2.JPG)`

GitHub側のURLルーティングの都合上、パスは大文字小文字含めて完全一致している必要があります。

（なお、ブランチ名はただのタグに過ぎないため、2バイト文字などを入れない限り問題は起こりません。）

2022-08-27 13:59 UTC, Ryosei-IT commented
なるほど、パスが小文字になっている点は気づかなかった。訂正しました。ありがとう🙏

2022-08-31 20:49 UTC, NakagawaRyunosuke submitted a review, later dismissed
@Ryosei-it
誤字を見つけました、まだマージしないでください。すみません…

2022-09-01 14:05 UTC, Ryosei-IT commented
@NakagawaRyunosuke これで再度レビュー依頼できているのだろうか、、？
よろしくお願いします🙏

2022-09-02 02:11 UTC, NakagawaRyunosuke reviewed
29行目あたりから少し見にくい気がしますが、内容としては良いと思います！

2022-09-02 07:40 UTC, quadseed requested changes
コメントした点について確認してください

また、全体として結果を書くときに「確認できた」で済ませるのではなく、確認のために使用したコマンドの出力結果を合わせて記述すると、より分かりやすいものになると思います

2022-09-02 07:40 UTC, quadseed commented on 20220809-NAT_DHCP.md
> +    ### 結果：仮説通りにInside globalに1172.16.0.2が、Inside localには192.168.0.10が登録がされていた。
Inside globalのIPアドレスが正しくありません

2022-09-02 07:40 UTC, quadseed commented on 20220809-NAT_DHCP.md
> +    仮説：現在設定しているアドレスプールからは３つのIPアドレスが割り振れるため、2代接続時には66%ほどの使用率、１台増やせば100%になる。<br>
誤字があります 

`2代` -> `2台`

2022-09-02 07:40 UTC, quadseed commented on 20220809-NAT_DHCP.md
> +    上記コマンドを打つとallocated 2 (66%)との表示がされた。また、小津くんPC(PC4)を192.168.0.30として接続すると残りのアドレスが払い出され、allocated 3(100%)が確認できた。
実験レポートに個人名を記述しないでください

特定の端末を指したいときは初めに固有の名称を与えて（例: PC1）、その固有名を用いるようにしてください

2022-09-02 07:40 UTC, quadseed commented on 20220809-NAT_DHCP.md
> +    <p>PC1及びPC2に加え、小津くんのPC3の3台をRTに繋げた際にDHCP poolの払い出し状況を確認する(#show ip dhcp pool)</p>
実験レポートに個人名を記述しないでください

2022-09-02 07:40 UTC, quadseed commented on 20220809-NAT_DHCP.md
> +    <p>PC1、PC2、小津くんのPC3をRTに繋げた際にPCに割り振られたIPと、RTの情報が一致するか確認する(#show ip dhcp binding)</p>
実験レポートに個人名を記述しないでください

2022-09-02 07:40 UTC, quadseed commented on 20220809-NAT_DHCP.md
> +- 完全にDHCPサーバが見つからない場合はAPIPAにによって自動設定がされる。<br>
誤字を修正してください

2022-09-02 12:23 UTC, Ryosei-IT commented
訂正箇所の指摘ありがとう！明日中に訂正します🫡
次回以降は誤字らないようにと出力結果も合わせて記載しまます！

2022-09-03 05:39 UTC, quadseed approved these changes
Good!

2022-09-11 13:21 UTC, merged